name: Setup Node.js
description: Setups Node.js and restores Yarn cache
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "lts/*"
        cache: "yarn"

    - name: Check config
      id: yarn-config
      shell: bash
      run: echo "CACHE=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Restore cache
      uses: actions/cache@v6
      with:
        path: ${{ steps.yarn-config.outputs.CACHE }}
        key: yarn-cache-${{ runner.os }}-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}
        restore-keys: yarn-cache-${{ runner.os }}-
