name: Build Artifact
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_call:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Yarn
        uses: ./.github/actions/setup

      - name: Build Package
        run: |
          yarn install --immutable
          yarn build

